### ISSUE TITLE
Why does upload() not execute callback on success?

### ISSUE THREAD

**Issue by gerbil** [jeduan/playup#10]
publisher.upload('test.apk', {
        track: 'production',        
        recentChanges: {
            'en-US': 'test'
        }
    }, function (err) {
        if (err) {throwsError(err);}

       // THIS WILL NEVER WORK
        fs.unlinkSync('test.apk');
        done();
    });

**Comment by jeduan** [comment]
Hi. I run this on a gulp task so in my case it does execute the callback. Can you run your script with `DEBUG= google-play-publisher node script.js` and paste the output?

**Comment by gerbil** [comment]
I did the same. I guess you forgot to include callback() reference in .upload near here:

`], function (err) {
    if (err) return callback(err)
	callback()
    debug('> Finished uploading APK')
  })`

**Comment by jeduan** [comment]
@gerbil hey, can you test on the newest package (playup) ?

**Comment by jeduan** [comment]
closing. If the issue persists please reopen this
