### ISSUE TITLE
Can't require this module

### ISSUE THREAD

**Issue by julianchurchill** [jeduan/playup#11]
Just did 'npm install --save playup' and the following to my gulpfile.js:

```javascript
var publisher = require('playup')({
  client_email: '',
  private_key: '',
})
```

Then when running gulp I get "Cannot find module 'playup'".  I suspect it is because package.json lists main as index.js, but I don't see an index.js in the playup module...

**Comment by jeduan** [comment]
@julianchurchill Thanks for the report! I just published version 1.0.2 which fixes this issue
