### ISSUE TITLE
please use co instead of old school async.

### ISSUE THREAD

**Issue by kilianc** [jeduan/playup#3]

**Comment by jeduan** [comment]
I'm waiting for await/async actually.

**Comment by ronkorving** [comment]
Why is this an issue? Who stands to benefit? You can make this issue on virtually every package on npm...

Anyway, would much rather use `await` too ;)

**Comment by kilianc** [comment]
@ronkorving me and @jeduan work together and it was more of a "nice to have" -- "reminder" for us internally than a bug. I would say a test suite has higher priority than this.

**Comment by kilianc** [comment]
Also

> Who stands to benefit?

Us when we write code :)

**Comment by ronkorving** [comment]
Understood :)

**Comment by jeduan** [comment]
Using Promises as of 91bad17816
